### ISSUE TITLE
Enums do not take __attribute__((packed)) into account.

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#301]
I think align on enums works, but this doesn't
```c
typedef enum {
    F1 = 1,
} __attribute__((packed)) A;

_Static_assert(sizeof(A) == 1, "");
_Static_assert(_Alignof(A) == 1, "");
```

**Comment by ehaas** [comment]
There are several things we need to do to implement this:

1. Trailing attributes are not being added to the type (same as #295 but in `enumSpec`)
2. The types of enumerator constants should just use C integer promotion rules instead of the `fshort-enums` setting; enumerator constants defined in the same enum do not have to be the same type:
```c
enum A {
        A1 = -1,
        A2 = 0,
        A3 = 4294967295,
        A4 = 4294967296
};

_Static_assert(__builtin_types_compatible_p(typeof(A1), typeof(A2)), "should be compatible");
_Static_assert(!__builtin_types_compatible_p(typeof(A1), typeof(A3)), "should not be compatible");
_Static_assert(sizeof(A2) == sizeof(int), "size");
_Static_assert(sizeof(A4) == sizeof(long), "size");
_Static_assert(sizeof(enum A) == sizeof(long), "size");
```
3. The `tag_ty` of an enum can't be computed until the entire enum is parsed (including trailing attributes, if any). If the enum is not packed (via an attribute or `-fshort-enums`) then the underlying type is the first from this list that can hold all the enum values (this is what I got testing with clang and gcc on MacOS and Linux, respectively; IIRC MSVC on windows might try signed types first) : `unsigned int`, `int`, `unsigned long`, `long`, `unsigned long long`, `long long`. If the enum is packed, then it tries `unsigned char`, `signed char`, `unsigned short`, `short` before the preceding list.
