### ISSUE TITLE
Can't run binary outside of project directory.

### ISSUE THREAD

**Issue by TwoClocks** [Vexu/arocc#598]
if you copy the `arocc` bin and a `c` file out of the project directory, it fails with 
`fatal error: unable to find Aro builtin headers`

It looks like `Complation.defineSystemIncludes` walks the file system from the binary upwards, looking for `include/stddef.h`. So if you move the binary outside the project tree... no bueno.

With some guidance, I can take a stab at it. Do you want to just embed the file(s), or add a build step to compress them first? or other?

**Comment by Vexu** [comment]
GCC fails with `gcc: fatal error: cannot execute ‘cc1’: execvp: No such file or directory` when moved out of installation directory and clang ignores the failure so that you get an error when trying to include `stdalign.h` for example.

Based on that the current behavior is fine but if you want this to work then you can just make that a non-fatal error.
